---
- name: Check for client configuration
  stat:
    path: "{{ ipsec_client_config_dir }}/{{ client.name }}.sswan"
  register: client_androidconfig
  tags: ['ipsec_client_configs']

- name: Create identifier
  command: uuidgen
  register: identifier
  when: not client_androidconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: Ensure client config
  template:
    src: android.sswan
    dest: "{{ ipsec_client_config_dir }}/{{ client.name }}.sswan"
    owner: root
    group: root
    mode: 0600
  when: not client_androidconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: VPN | Client config creation | Fetch ios config to localhost
  fetch:
    src: "{{ ipsec_client_config_dir }}/{{ client.name }}.sswan"
    dest: "/tmp/ipsec_vpn/{{ ipsec_prefix }}_{{ client.name }}.sswan"
    flat: yes
  tags: ['ipsec_client_configs']
