---
- name: Check for client configuration
  stat:
    path: "{{ ipsec_client_config_dir }}/{{ client.name }}.mobileconfig"
  register: client_mobileconfig
  tags: ['ipsec_client_configs']

- name: Create new payload identifier
  command: uuidgen
  register: payload_identifier
  when: not client_mobileconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: Create new payload uuid
  command: uuidgen
  register: payload_uuid
  when: not client_mobileconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: Create second payload identifier
  command: uuidgen
  register: payload_identifier_second
  when: not client_mobileconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: Create second payload uuid
  command: uuidgen
  register: payload_uuid_second
  when: not client_mobileconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: Ensure client config
  template:
    src: mobileconfig
    dest: "{{ ipsec_client_config_dir }}/{{ client.name }}.mobileconfig"
    owner: root
    group: root
    mode: 0600
  register: client_conf
  when: not client_mobileconfig.stat.exists
  tags: ['ipsec_client_configs']

- name: VPN | Client config creation | Fetch ios config to localhost
  fetch:
    src: "{{ ipsec_client_config_dir }}/{{ client.name }}.mobileconfig"
    dest: "/tmp/ipsec_vpn/{{ ipsec_prefix }}_{{ client.name }}.mobileconfig"
    flat: yes
  tags: ['ipsec_client_configs']

- name: VPN | Client config sending | Send configs to user email
  mail:
    host: "{{ ipsec_mail.host }}"
    port: "{{ ipsec_mail.port }}"
    username: "{{ ipsec_mail.user }}"
    sender: "{{ ipsec_mail.user }}"
    password: "{{ ipsec_mail.secret }}"
    to: "{{ client.email }}"
    subject: "{{ ipsec_mail.subject }} (IOS confs)"
    body: "{{ ipsec_mail.body }}"
    attach: 
      - "{{ ipsec_client_config_dir }}/{{ client.name }}.mobileconfig"
  when: client.email is defined and ipsec_mail.host is defined and client_conf.changed
  failed_when: False
  tags: ['ipsec_client_configs']
