---
- name: VPN | IPtables | Ensure iptables rules
  shell:
    cmd: |
      iptables -P INPUT   ACCEPT
      iptables -P FORWARD ACCEPT
      iptables -P OUTPUT  ACCEPT

      iptables -F
      iptables -t nat -F
      iptables -t mangle -F

      # INPUT

      # accept anything already accepted
      iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

      # accept anything on the loopback interface
      iptables -A INPUT -i lo -j ACCEPT

      # drop invalid packets
      iptables -A INPUT -m state --state INVALID -j DROP

      # rate-limit repeated new requests from same IP to any ports
      iptables -I INPUT -m state --state NEW -m recent --set
      iptables -I INPUT -m state --state NEW -m recent --update --seconds 300 --hitcount 60 -j DROP

      # accept (non-standard) SSH
      iptables -A INPUT -p tcp --dport {{ ansible_port }} -j ACCEPT

      # VPN

      # accept IPSec/NAT-T for VPN (ESP not needed with forceencaps, as ESP goes inside UDP)
      iptables -A INPUT -p udp --dport  500 -j ACCEPT
      iptables -A INPUT -p udp --dport 4500 -j ACCEPT

      # forward VPN traffic anywhere
      iptables -A FORWARD --match policy --pol ipsec --dir in  --proto esp -s {{ ipsec_vpn_network }} -j ACCEPT
      iptables -A FORWARD --match policy --pol ipsec --dir out --proto esp -d {{ ipsec_vpn_network }} -j ACCEPT

      # reduce MTU/MSS values for dumb VPN clients
      iptables -t mangle -A FORWARD --match policy --pol ipsec --dir in -s {{ ipsec_vpn_network }} -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360

      # masquerade VPN traffic over eth0 etc.
      iptables -t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -m policy --pol ipsec --dir out -j ACCEPT  # exempt IPsec traffic from masquerading
      iptables -t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -j MASQUERADE

      # fall through to drop any other input and forward traffic

      iptables -A INPUT   -j DROP
      iptables -A FORWARD -j DROP

- name: VPN | IPtables | Save rules
  shell:
    cmd: |
      iptables-save > /etc/iptables/rules.v4
